### ISSUE TITLE
今日更新的 FEX技术周刊 - 06/27期 RSS 日期显示错误

### ISSUE THREAD

**Issue by yangzj1992** [fex-team/fex-team.github.io#34]
如图。   ![RSS日期错误](http://ww3.sinaimg.cn/large/0060lm7Tgw1f59r6la5h9j31iy0lydog.jpg)

**Comment by hefangshi** [comment]
目前已经修复了，但是已经被抓取的rss错误就无法解决了。

另：你这个工具叫什么？

**Comment by yangzj1992** [comment]
好的， 工具是这个：[reeder](http://reederapp.com/mac/)

**Comment by hefangshi** [comment]
感谢~
